### ISSUE TITLE
Add qualifiedName query to AbstractProperty

### ISSUE THREAD

**Issue by scheibel** [cginternals/cppexpose#36]
This member function replaces the current implementation in gloperate ```Stage``` and ```AbstractSlot```.

**Comment by sbusch42** [comment]
This might not give the intended effect, because the object hierarchy can be larger than expected. For example in gloperate, we might want to get the name of a slot relative to the pipeline, however if we implement this at such a global level, we might get e.g. "gloperate.canvas0.pipeline.stage1.slot1" instead of "stage1.slot1". So we should at least add an optional parameter that defines the root object which shall be used.

**Comment by scheibel** [comment]
Implemented in #60.
