### ISSUE TITLE
Allow multiple global script objects

### ISSUE THREAD

**Issue by j-o** [cginternals/cppexpose#45]
Or: Why does this limitation exist?

Motivation: in gloperate, the Environment registers itself as global object called `gloperate`. An application can either add properties and functions to that (e.g., `gloperate.myapp.somefunc()`) or replace the global object and add the Environment as property (e.g., `myapp.gloperate.system.exit()`). Neither seems appropriate (nor convenient) for orthogonal functionalities.

Alternative solution: Don't add the global object itself, but directly its properties and functions, removing the need to qualify access with its name.

**Comment by sbusch42** [comment]
It does exist because it is just not possible to do this in the QML backend. That would need a way to dynamically add custom properties (which are then exposed to the qml scripting backend), and this is not possible. It could be done statically, but that would mean that we need to know the names of the objects in beforehand (thats the reason why there is only one, named "gloperate").

It would be no problem at all to do this in the duktape backend. But then we have a serious incompatibility between the two backends, so if I write for one backend, it will most propably not work anymore with the other....

**Comment by j-o** [comment]
http://doc.qt.io/qt-5/qjsengine.html#globalObject seems to serve exactly that purpose. Since `gloperate_qtquick::QmlEngine` ultimately inherits `QJSEngine`, this should be applicable.
A quick test confirms that it is working: https://gist.github.com/j-o/6c33d709ca64723b93d1551555b8cc88 (quick hack of gloperate-viewer/main.cpp)

**Comment by sbusch42** [comment]
Thinking about this a bit longer, I must say that I am not at all satisfied with the QML scripting backend. In addition to the limitation you mentioned, there are others we have to deal with sooner or later. For example, since the global object is read-only, defining a function a variable once and referencing it later does not work. Therefore, scripts would have to be written in a way that they use a global object instead (e.g., global.myFunction = ...). This is not what I would expect from a javascript scripting environment and is in fact also an incompatibility to the duktape backend, which has no such limitations.

Therefore, I would suggest that we rewrite the scripting integration like this:
- Always use the duktape backend for scripting in gloperate
- Use the QML-integration only to allow QML UIs to interact with the gloperate environment (e.g., the pipeline editor), but do not execute gloperate scripts within the QML javascript environment

This way we could get rid of the limitations of the QML scripting environment for the general scripting, and for the UI integration, certain limitations or differences would not be much of a problem (e.g., accessing global objects via app.globalName instead of just globalName).

**Comment by sbusch42** [comment]
About globalObject: Yes, in QJSEngine it works, but in QML. a specialized JS engine is used in which the global object is constant.

**Comment by sbusch42** [comment]
If you can turn that quick-hack into a working solution that takes a cppexpose::Object and creates a QObject wrapper for it, which can then be registered at the global object, we can use it. But I doubt that will work, because I spent a week last year on this problem and it didn't work in the end.

**Comment by j-o** [comment]
The quick-hack from the gist does exactly that:
```
MyObject obj;
QmlObjectWrapper objWrapper(&app.qmlEngine(), &obj);
app.qmlEngine().globalObject().setProperty("foobar", objWrapper.wrapObject());
```
I can access functions and properties from `MyObject`, e.g., enter `foobar.print(foobar.string)` in the gloperate viewer's script console and get the expected result ("Hallo" printed to stdout). Or is there more to it that I did not understand?

`app.qmlEngine().globalObject()` returns a `QJSValue` which is not a `QObject`, so calling `setProperty` doesn't actually have anything to do with the Qt property system (I think), but directly sets the properties of the JS object. So unless an actual `QObject` is somehow required to interact with QML, the above lines should do the trick.
